export default  {
    products: [
        {
        _id: '1',
        name: 'A Game of Thrones',
        image: '/images/GameOfThronesCover.jpeg',
        price: 21.94,
        author: 'George R.R. Martin',
        rating: 4.7,
        numReviews: 2431,
        description: "Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off King’s Landing. There Eddard Stark of Winterfell rules in Robert’s name.",
        genre: "Fantasy",
        publisher: "Bantam",
        pubdate: "08/04/1997",
        authordescript: "is an American novelist and short story writer, screenwriter, and television producer. He is the author of the series of epic fantasy novels A Song of Ice and Fire, which was adapted into the Emmy Award-winning HBO series Game of Thrones."
    },
    {
        _id: '2',
        name: "Harry Potter and the Sorceror's Stone",
        image: '/images/HarryPotterCover.jpeg',
        price: 12.99,
        author: 'J.K. Rowling', 
        rating: 5.0,
        numReviews: 1284,
        description: "All he knows is a miserable life with the Dursleys, his horrible aunt and uncle, and their abominable son, Dudley - a great big swollen spoiled bully. Harry's room is a tiny closet at the foot of the stairs, and he hasn't had a birthday party in eleven years.",
        genre: "Fantasy",
        publisher: "Bloomsbury (UK)",
        pubdate: "06/27/1997",
        authordescript: "is a British author, philanthropist, film producer, television producer, and screenwriter. She is best known for writing the Harry Potter fantasy series, which has won multiple awards and sold more than 500 million copies."
    },
    {
        _id: '3',
        name: 'Dune',
        image: '/images/DuneCover.png',
        price: 9.99,
        author: 'Frank Herbert',
        rating: 4.6,
        numReviews: 651,
        description: "Arguably a masterpiece of the Science Fiction genre, Dune laid the foundation for many of the epics that followed its publication. Herbert addresses overarching themes of family politics, religion, environment, and the all-encompassing temptation of power, all set against the backdrop of a futuristic civilization that, at times, can be unflinchingly prophetic.",
        genre: "Science Fiction",
        publisher: "Chilton Books",
        pubdate: "08/20/1965",
        authordescript: "was an American science fiction author best known for the 1965 novel Dune and its five sequels. Though he became famous for his novels, he also wrote short stories and worked as a newspaper journalist, photographer, book reviewer, ecological consultant, and lecturer."
    },
    {
        _id: '4',
        name: '1984',
        image: '/images/1984Cover.jpeg',
        price: 7.48,
        author: 'George Orwell',
        rating: 4.7,
        numReviews: 1409,
        description: "Written more than 70 years ago, 1984 was George Orwell’s chilling prophecy about the future. And while 1984 has come and gone, his dystopian vision of a government that will do anything to control the narrative is timelier than ever...",
        genre: "Science Fiction",
        publisher: "Secker & Warburg",
        pubdate: "06/08/1949",
        authordescript: "was an English novelist, essayist, journalist and critic. His work is characterised by lucid prose, biting social criticism, opposition to totalitarianism, and outspoken support of democratic socialism."
    },
    {
        _id: '5',
        name: 'The Lord of the Rings',
        image: '/images/TheLordOfTheRingsCover.jpeg',
        price: 24.99,
        author: 'J. R. R. Tolkein',
        rating: 4.7,
        numReviews: 934,
        description: "In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. ",
        genre: "Fantasy",
        publisher: "Allen & Unwin",
        pubdate: "07/29/1954",
        authordescript: "was an English writer, poet, philologist, and academic, best known as the author of the high fantasy works The Hobbit and The Lord of the Rings."
    },
    {
        _id: '6',
        name: 'Fahrenheit 451',
        image: '/images/Fahrenheit451Cover.jpeg',
        price: 15.49,
        author: 'Ray Bradbury',
        rating: 4.6,
        numReviews: 1402,
        description: "Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden.",
        genre: "Science Fiction",
        publisher: "Simon & Schuster",
        pubdate: "04/20/2019",
        authordescript: "was an American author and screenwriter. One of the most celebrated 20th-century American writers, he worked in a variety of modes, including fantasy, science fiction, horror, mystery, and realistic fiction."
    },
    {
        _id: '7',
        name: 'Neuromancer',
        image: '/images/NeuromancerAltCover.jpeg',
        price: 16.99,
        author: 'William Gibson',
        rating: 4.4,
        numReviews: 859,
        description: "Case was the sharpest data-thief in the matrix—until he crossed the wrong people and they crippled his nervous system, banishing him from cyberspace. Now a mysterious new employer has recruited him for a last-chance run at an unthinkably powerful artificial intelligence.",
        genre: "Science Fiction",
        publisher: "Penguin Publishing Group",
        pubdate: "07/01/2000",
        authordescript: "is an American-Canadian speculative fiction writer and essayist widely credited with pioneering the science fiction subgenre known as cyberpunk. Beginning his writing career in the late 1970s, his early works were noir, near-future stories that explored the effects of technology, cybernetics, and computer networks on humans—a 'combination of lowlife and high tech' and helped to create an iconography for the information age before the ubiquity of the Internet in the 1990s."
    },
    {
        _id: '8',
        name: 'The Two Towers',
        image: '/images/TheTwoTowersCover.jpeg',
        price: 8.99,
        author: 'J. R. R. Tolkein',
        rating: 4.7,
        numReviews: 784,
        description: "Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom.",
        genre: "Fantasy",
        publisher: "Random House Publishing Group",
        pubdate: "08/12/1986",
        authordescript: "was an English writer, poet, philologist, and academic, best known as the author of the high fantasy works The Hobbit and The Lord of the Rings."
    },
    {
        _id: '9',
        name: 'Brave New World',
        image: '/images/BraveNewWorldCover.jpeg',
        price: 14.49,
        author: 'Aldous Huxley',
        rating: 4.2,
        numReviews: 1728,
        description: "Aldous Huxley's profoundly important classic of world literature, Brave New World is a searching vision of an unequal, technologically-advanced future where humans are genetically bred, socially indoctrinated, and pharmaceutically anesthetized to passively uphold an authoritarian ruling order–all at the cost of our freedom, full humanity, and perhaps also our souls.",
        genre: "Science Fiction",
        publisher: "Chatto & Windus",
        pubdate: "1932",
        authordescript: "was an English writer and philosopher. He wrote nearly 50 books—both novels and non-fiction works—as well as wide-ranging essays, narratives, and poems. Born into the prominent Huxley family, he graduated from Balliol College, Oxford, with an undergraduate degree in English literature."
    }
]
}